# Copyright (c) 2021, Teslabs Engineering S.L.
# SPDX-License-Identifier: Apache-2.0

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: spinner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: spinner
          toolchains: arm-zephyr-eabi

      - name: Lint code
        run: |
          git diff --name-only ${{ github.base_ref}} ${{ github.sha }} -- '*.[ch]' | xargs zephyr/scripts/checkpatch.pl

      - name: Build
        working-directory: spinner
        run: |
          west twister -T spinner -v --inline-logs --integration

      - name: Test
        working-directory: spinner
        run: |
          west twister -T tests -v --inline-logs --integration
